# Generated by Django 5.1 on 2024-08-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(default='Delicious Delight!', max_length=500),
        ),
    ]
