# Generated by Django 5.1 on 2024-08-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_locat',
            field=models.CharField(default='images/dish1.jpeg', max_length=50),
        ),
    ]
